name: Reusable - Terraform

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
        description: 'Diretório onde executar os comandos Terraform'
      auto_apply:
        required: false
        type: boolean
        default: false
      var_file:
        required: false
        type: string
        description: 'Arquivo de variáveis .tfvars (opcional)'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          if [ -n "${{ inputs.var_file }}" ]; then
            terraform plan -no-color -input=false -var-file="${{ inputs.var_file }}"
          else
            terraform plan -no-color -input=false
          fi
        continue-on-error: true

      - name: Comment PR with plan details
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### 📁 Directory: \`${{ inputs.working_directory }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: ${{ inputs.auto_apply && github.event_name == 'push' }}
        run: |
          if [ -n "${{ inputs.var_file }}" ]; then
            terraform apply -no-color -input=false -auto-approve -var-file="${{ inputs.var_file }}"
          else
            terraform apply -no-color -input=false -auto-approve
          fi
