name: Deploy SQL Database

on:
  workflow_run:
    workflows: ["Deploy RDS Infrastructure"]
    types:
      - completed
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  verify-sql:
    if: github.event.workflow_run.conclusion == 'success'
    uses: fiap-soat-grupo36/reusable-actions/.github/workflows/_reusable-terraform.yml@main
    with:
      workspace: ${{ github.event.workflow_run.head_branch == 'main' && 'prod' || 'dev' }}
      environment: ${{ github.event.workflow_run.head_branch == 'main' && 'prod' || 'dev' }}
      working_directory: ./sql
      tfvars_file: ${{ github.event.workflow_run.head_branch == 'main' && 'environments/prod.tfvars' || 'environments/dev.tfvars' }}
      auto_apply: false
      localstack_pod: fiap
    secrets:
      LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

  deploy-sql-dev:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop'
    needs: verify-sql
    uses: fiap-soat-grupo36/reusable-actions/.github/workflows/_reusable-terraform.yml@main
    with:
      workspace: dev
      environment: dev
      working_directory: ./sql
      tfvars_file: 'environments/dev.tfvars'
      auto_apply: true
      localstack_pod: fiap
    secrets:
      LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

  deploy-sql-prod:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    needs: verify-sql
    uses: fiap-soat-grupo36/reusable-actions/.github/workflows/_reusable-terraform.yml@main
    with:
      workspace: prod
      environment: prod
      working_directory: ./sql
      tfvars_file: 'environments/prod.tfvars'
      auto_apply: true
      localstack_pod: fiap
    secrets:
      LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
